baseURL = "http://duncan.is/"
title = "Making a Pile of Photos"
theme = "william"

# Language config
languageCode = "en-gb"
defaultContentLanguage = "en-gb"

[languages]
  [languages.en-gb]
    weight = 1
    lang = "en-gb"

# Taxonomy config
[taxonomies]
  tag = "tags"