baseURL = "http://duncan.is/"
title = "Making a Pile of Photos"
copyright = "&copy; {year} Duncan McPherson, <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">CC-BY-NC-SA</a>."
theme = "william"

# Language config
languageCode = "en-gb"
defaultContentLanguage = "en-gb"

[languages]
  [languages.en-gb]
    weight = 1
    lang = "en-gb"

# Author - extra authors can be added
[author]
  name = "Duncan McPherson"
  bio = ""
  email = ""
  [social]
    facebook      = "full profile url in facebook"
    github        = "full profile url in github"
    googleplus    = "full profile url in googleplus"
    instagram     = "full profile url in instagram"
    linkedin      = "full profile url in linkedin"
    pinterest     = ""
    skype         = ""
    stackoverflow = "full profile url in stackoverflow"
    twitter       = "full profile url in twitter"
    website       = ""
    youtube       = ""
    # add any others you like in here, but be prepared to do some work to make sure they function


# Site parameters
[params]
  description = "A pile of photos that I took and still like."

# Taxonomy config
[taxonomies]
  tag = "tags"
